Resources:
  FactionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.factionsTableName}
      AttributeDefinitions:
        - AttributeName: factionID
          AttributeType: S
      KeySchema:
        - AttributeName: factionID
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
