Resources:
  GameRulesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.gameRulesTableName}
      AttributeDefinitions:
        - AttributeName: gameRuleID
          AttributeType: S
      KeySchema:
        - AttributeName: gameRulesID
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST