Resources:
  BeastsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.beastsTableName}
      AttributeDefinitions:
        - AttributeName: factionName
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: factionName
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST